[package]
name = "snowflake"
version = "0.1.0"
authors = ["Kyle Murphy <kyle.murphy@aspect.com>"]

[dependencies]
openssl = "0.7"
openssl-sys = "0.7"
hyper = "0.9"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
chrono = "0.2"
base32 = "0.3"
env_logger = "0.3"
log = "0.3"
envoption = "0.2"
